# <font color='navy'>Business Context:</font>
* Attrition refers to the rate at which members of a workforce leave the company over a specific period, often measured annually. It is a natural part of business operations but can become problematic if the rate is high.
* Attrition includes employees who leave for various reasons, such as retirement, resignation, termination, or transfer to other locations. This metric is crucial for companies to track and analyze because it impacts staffing levels, workforce planning, and overall organizational efficiency.
* Predicting employee attrition is crucial for companies because it helps manage costs and maintain operational stability. High turnover rates can lead to significant expenses related to recruiting, hiring, and training new staff. Moreover, frequent turnover can disrupt workflow, impact team dynamics, and erode knowledge within a company
* By using analytics to predict when employees might leave, companies can implement targeted retention strategies, optimize their workforce planning, and ultimately sustain a more stable and experienced workforce. This proactive approach allows businesses to maintain productivity and competitiveness in their industry.

# Coding Questions

## Question 1
* Read the hr analytics dataset that is shared with you on G-Drive with the following link and save it to a variable called `data_hr`:

> * https://drive.google.com/file/d/1-SGPhmw4F7hzBxeJv49lkHwj8yEGgG7S/view?usp=sharing

* If you reach G_drive Limit Warning, use the Github link below

> * https://raw.githubusercontent.com/marineevy/datasets/main/hr_analytics.csv

* If the above options do not work due to download limits, upload the data onto Colab session and read it directly from your Colab session.

In [47]:
# your code goes in her
import pandas as pd

data_hr = pd.read_csv('data_hr.csv')

## Question 2
* Inspect the Dataframe using the describe() function. include all variables.

In [45]:
# your code goes in here
data_hr.describe(include = 'all')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,...,PerformanceRating,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470,1470,1470.000000,1470,1470.000000,1470.000000,1470,1470.0,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
unique,NaN,2,3,NaN,3,NaN,NaN,6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,No,Travel_Rarely,NaN,Research & Development,NaN,NaN,Life Sciences,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1233,1043,NaN,961,NaN,NaN,606,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,36.923810,NaN,NaN,802.485714,NaN,9.192517,2.912925,NaN,1.0,1024.865306,...,3.153741,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,NaN,NaN,403.509100,NaN,8.106864,1.024165,NaN,0.0,602.024335,...,0.360824,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,NaN,NaN,102.000000,NaN,1.000000,1.000000,NaN,1.0,1.000000,...,3.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,NaN,NaN,465.000000,NaN,2.000000,2.000000,NaN,1.0,491.250000,...,3.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,NaN,NaN,802.000000,NaN,7.000000,3.000000,NaN,1.0,1020.500000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,NaN,NaN,1157.000000,NaN,14.000000,4.000000,NaN,1.0,1555.750000,...,3.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,NaN,NaN,1499.000000,NaN,29.000000,5.000000,NaN,1.0,2068.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [49]:
print(data_hr.describe(include = 'all'))

                Age Attrition BusinessTravel    DailyRate  \
count   1470.000000      1470           1470  1470.000000
unique          NaN         2              3          NaN
top             NaN        No  Travel_Rarely          NaN
freq            NaN      1233           1043          NaN
mean      36.923810       NaN            NaN   802.485714
std        9.135373       NaN            NaN   403.509100
min       18.000000       NaN            NaN   102.000000
25%       30.000000       NaN            NaN   465.000000
50%       36.000000       NaN            NaN   802.000000
75%       43.000000       NaN            NaN  1157.000000
max       60.000000       NaN            NaN  1499.000000

                    Department  DistanceFromHome    Education EducationField  \
count                     1470       1470.000000  1470.000000           1470
unique                       3               NaN          NaN              6
top     Research & Development               NaN          NaN  Life Sciences
freq                       961               NaN          NaN            606
mean                       NaN          9.192517     2.912925            NaN
std                        NaN          8.106864     1.024165            NaN
min                        NaN          1.000000     1.000000            NaN
25%                        NaN          2.000000     2.000000            NaN
50%                        NaN          7.000000     3.000000            NaN
75%                        NaN         14.000000     4.000000            NaN
max                        NaN         29.000000     5.000000            NaN

        EmployeeCount   EmployeeID  ... PerformanceRating  StandardHours  \
count          1470.0  1470.000000  ...       1470.000000         1470.0
unique            NaN          NaN  ...               NaN            NaN
top               NaN          NaN  ...               NaN            NaN
freq              NaN          NaN  ...               NaN            NaN
mean              1.0  1024.865306  ...          3.153741           80.0
std               0.0   602.024335  ...          0.360824            0.0
min               1.0     1.000000  ...          3.000000           80.0
25%               1.0   491.250000  ...          3.000000           80.0
50%               1.0  1020.500000  ...          3.000000           80.0
75%               1.0  1555.750000  ...          3.000000           80.0
max               1.0  2068.000000  ...          4.000000           80.0

        StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
count        1470.000000        1470.000000           1470.000000
unique               NaN                NaN                   NaN
top                  NaN                NaN                   NaN
freq                 NaN                NaN                   NaN
mean            0.793878          11.279592              2.799320
std             0.852077           7.780782              1.289271
min             0.000000           0.000000              0.000000
25%             0.000000           6.000000              2.000000
50%             1.000000          10.000000              3.000000
75%             1.000000          15.000000              3.000000
max             3.000000          40.000000              6.000000

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000
unique             NaN             NaN                 NaN
top                NaN             NaN                 NaN
freq               NaN             NaN                 NaN
mean          2.761224        7.008163            4.229252
std           0.706476        6.126525            3.623137
min           1.000000        0.000000            0.000000
25%           2.000000        3.000000            2.000000
50%           3.000000        5.000000            3.000000
75%           3.000000        9.000000            7.000000
max           4.000000       40.000000           18.000000

        YearsSinceLastPromotion YearsWithCurrManager
count               1470.000000          1470.000000
unique                      NaN                  NaN
top                         NaN                  NaN
freq                        NaN                  NaN
mean                   2.187755             4.123129
std                    3.222430             3.568136
min                    0.000000             0.000000
25%                    0.000000             2.000000
50%                    1.000000             3.000000
75%                    3.000000             7.000000
max                   15.000000            17.000000

[11 rows x 32 columns]

In [50]:
data_hr.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeID,HourlyRate,JobInvolvement,JobLevel,MonthlyIncome,...,PerformanceRating,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,65.891156,2.729932,2.063946,6502.931293,...,3.153741,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,20.329428,0.711561,1.106940,4707.956783,...,0.360824,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,30.000000,1.000000,1.000000,1009.000000,...,3.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,48.000000,2.000000,1.000000,2911.000000,...,3.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,66.000000,3.000000,2.000000,4919.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,83.750000,3.000000,3.000000,8379.000000,...,3.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,100.000000,4.000000,5.000000,19999.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

## Question 3
* What is the dataset dimension (number of rows and columns)

In [53]:
# your code goes in here
data_hr.shape

(1470, 32)

In [34]:
n_rows, n_cols = data_hr.shape
print("Rows:", n_rows)
print("Columns:", n_cols)

Rows: 1470
Columns: 32

## Question 4:
* identify the variables witha numerical data type and save them to `numerical_variables` as a list
* identify the variables witha categorical data type and save them to `categorical_variables` as a list

In [33]:
data_hr.dtypes

Age                         int64
Attrition                  object
BusinessTravel             object
DailyRate                   int64
Department                 object
DistanceFromHome            int64
Education                   int64
EducationField             object
EmployeeCount               int64
EmployeeID                  int64
Gender                     object
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                    object
MaritalStatus              object
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                     object
OverTime                   object
PercentSalaryHike           int64
PerformanceRating           int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [54]:
# your code goes in here
categorical_variable = data_hr.select_dtypes(include = object).columns. to_list
categorical_variables

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [55]:
from numpy import number
numarical_variable = data_hr.select_dtypes(include = number).columns. to_list
numerical_variables_variables

NameError: name 'numerical_variables_variables' is not defined

## Question 5
* how many employees are older than 60 years old
* save this number to a variable named `num_senior_employees`

In [60]:
sum(data_hr['Age']>60)

0

In [35]:
data_hr.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeID', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobRole', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [57]:
# your code goes in her

num_senior_employees = (data_hr['age'] > 60).sum()
print(num_senior_employees)

KeyError: 'age'

## Question 6
* how many employees are between 30 and 50 years old and have a performance rating greater or equal to 4
* save this resukt to a variable named `high_perf_employee_30_50`

In [61]:
mask_age_30 = data_hr['Age']>=30
mask_age_50 = data_hr['Age']<=50
mask_per_4 = data_hr['PerformanceRating']>=4
combined_mask = (mask_age_30 and mask_age_50 and mask_per_4)
high_perf_employee_30_50 = data_hr.csv [combined_mask].shape[0]
high_perf_employee_30_50

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [40]:
# your code goes in here
# condition 1: age between 30 and 50 (inclusive)
age_cond = (data_hr['Age'] >= 30) & (data_hr['Age'] <= 50)

# condition 2: performance rating >= 4
perf_cond = data_hr['PerformanceRating'] >= 4

# combine both conditions
both_cond = age_cond & perf_cond

# count how many rows satisfy both conditions
high_perf_employee_30_50 = both_cond.sum()
high_perf_employee_30_50

np.int64(156)

## Question 7
* What is the education field of the oldest employee who left the company (resigned - Attrition = Yes)
* save this result to a variable called `ed_field_oldest_resigned_employee`

In [ ]:
data_atr1 = data_hr['Attrition'] == 'Yes'
data_atr1['Age'].argmax
index_of_oldest person = data_atr_1['Age'].argmax

In [ ]:
# your code goes in here

resigned_df = df[df["Attrition"] == "Yes"]

# Find oldest age
oldest_age = resigned_df["Age"].max()

# Get employee(s) with that age
oldest_resigned = resigned_df[resigned_df["Age"] == oldest_age]

# Extract education field
ed_field_oldest_resigned_employee = oldest_resigned["EducationField"].values[0]

## Question 8
* What is the average monthly income for employees who resigned vs not resigned (Attririon = Yes vs Attririon = No)
* Save the monthly income of resigned customers to a variable named `mi_resigned` and save the the monthly income of not resigned (current) customers to a variable named `mi_current`
* Use groupby() for this analysis
* Interpret the result

In [65]:
# your code goes in here
mi_resigned = data_hr.groupby(by = "Attrition")['MonthlyIncome'].mean().Yes
mi_current = data_hr.groupby(by = "Attrition")['MonthlyIncome'].mean().No
print(mi_resigned,)

## Question 9
* For employees who have a job level of 2, what is the distribution of their performance ratings?
* Save the result to a variable named `perf_rating_job_level_2`.
* Use the `value_counts()` method for this analysis.
* Interpret the result.

In [ ]:
# Your code goes in here

## Question 10
* Encode the Attirion column with numbers using 0 and 1. Attrition = Yes should be 1 and Attrition = No should be 0.
* New data type of Attrition should be int
* Do not create a new variable, overwrite the existing Attrition variable

In [ ]:
# your code goes in here

## Question 11
* Investigate if there is correlation between Monthly Income and Attrition
* save this correlation to a variable named `corr_attrition_mi`
* interpret the result

In [ ]:
# your code goes in here

## Question 12
* Create a pivot table to show the average monthly income for each job level, grouped by attrition.
* Save the pivot table to a variable named `pivot_mi_job_level_attrition`.
* Interpret the results.

In [ ]:
# your code goes in here

## Question 13
* Create a pivot table to show the distribution of performance ratings for each education field, grouped by attrition.
* Save the pivot table to a variable named `pivot_perf_rating_edu_field_attrition`.
* Interpret the results.

In [ ]:
# your code goes in here

## Question 14
* Create a pivot table to show the average age of employees for each department, grouped by attrition.
* Save the pivot table to a variable named `pivot_age_dept_attrition`.
* Interpret the results.

In [ ]:
# your code goes in here

## Question 15
* How many employees have a monthly income greater than $10,000 and a performance rating of 4 or higher?

In [ ]:
# your code goes in here

## Question 16
* How many employees are male and have a job level of 4?

In [ ]:
# your code goes in here

## Question 17
* Identify employees who are older than 40 and have a performance rating greater than or equal to 4
* Then compute the interquartile range of their MonthlyIncome
* Save the interquartile range to a variable named iqr_4

* Identify employees who are older than 40 and have a performance rating less than or equal to 3
* Then compute the interquartile range of their MonthlyIncome
* Save the interquartile range to a variable named iqr_3

* Interpret the result

In [ ]:
# your code goes in here

# Question 18
* Compare the monthlyincome and performance rating of male and female employees using group by
* Interpret the results

In [ ]:
# your code goes in here